typography_spectrum: 0.5535328211262822
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.712434557499364
  lightness: 0.31680075149051845
  saturation: 0.8785923067480326
  rhythmicContrast: 0.9894050650764257
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.836187876528129
analytics:
  google: null
  facebook: null
  twitter: null
name: Wikihospitals
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Australian site
    url: 'http://www.wikihospitals.org/'
    type: external
  - name: ' Videos'
    id: 2dc8a33e-5bb6-4e00-a83b-f9cf6e574e5a
    type: content
  - name: Startups Database
    url: 'https://wikihospitals.knack.com/health-startups-australia#home/'
    type: external
favicon: null
title: A new world of information
description: 'Matching diseases, industry problems and startup solutions'
purpose: []
