name: Wikihospitals
favicon: null
layout_spectrum: 0.38392
typography_spectrum: 0.3225
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d281f'
    - '#e1dccc'
    - '#bab49c'
    - '#857f73'
    - '#781a10'
  brandStrength: 0.0625
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.5700805182568729
purpose: []
