typography_spectrum: 0.34067559731192887
color:
  brandColors:
    - '#CFC291'
    - '#FFF6C5'
    - '#A1E8D9'
    - '#FF712C'
    - '#695D46'
  brandStrength: 0.46579125756397843
  lightness: 0.28373689111322165
  saturation: 0.6344421103131026
  rhythmicContrast: 0.849716883385554
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8240843717940152
analytics:
  google: null
  facebook: null
  twitter: null
name: Wikihospitals
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Australian site
    url: 'http://www.wikihospitals.org/'
    type: external
  - name: ' Videos'
    id: 2dc8a33e-5bb6-4e00-a83b-f9cf6e574e5a
    type: content
favicon: null
title: A new world of information
description: 'Matching diseases, industry problems and startup solutions'
purpose: []
