typography_spectrum: 0.81139
color:
  brandColors:
    - '#2d281f'
    - '#e1dccc'
    - '#bab49c'
    - '#857f73'
    - '#781a10'
  brandStrength: 0.0625
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.5700805182568729
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.953
analytics:
  google: null
  facebook: null
  twitter: null
name: Wikihospitals
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: A new world of information
description: 'Match diseases, industry problems and startup solutions'
purpose: []
