name: Wikihospitals
favicon: null
layout_spectrum: 0.11725266673602164
typography_spectrum: 0.7986918434035033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.06257752166129649
  lightness: 0.7034428638871759
  saturation: 0.08796259108930826
  rhythmicContrast: 0.5700805182568729
purpose: []
